### ISSUE TITLE
packages not installed

### ISSUE THREAD

**Issue by pdi-uk** [medizininformatik-initiative/Projectathon6-miracum1#10]
After running the script runMIRACUM_select_step2.sh 
3 R packages are still missing: 

RANN, 
randomForest and
 kernlab

`[1] "Load weather data and find the appropriate stations for patients"
Fehler in loadNamespace(x) : es gibt kein Paket namens ‘RANN’`

**Comment by NandhiniS08** [comment]
Updated the script with the mentioned packages in the issue.
