### ISSUE TITLE
Cannot install R packages

### ISSUE THREAD

**Issue by stolzA** [medizininformatik-initiative/Projectathon6-miracum1#12]
Due to safety restrictions we cannot install R packages inside running docker containers. Is it possible to build an image with all necessary R packages preinstalled?

**Comment by NandhiniS08** [comment]
Yes Ill generate an image with preinstalled R packaged and push the iamge to DOckerhub.  Currently I am facing an issue with adding a package from the  BioConductor  family into docker. Ill update you as soon as its fixed

**Comment by mematt** [comment]
We are working on the solution, however we encountered some package dependency issues, which will take longer to solve. 
In the mean time, if possible could you create/use an R studio instance and install packages locally and then after isolating this machine from the internet, maybe try running the `step2` script. Step2 is self-contained and will not open any other ports or connect to the internet.

**Comment by NandhiniS08** [comment]
can you pull this image and test
_**docker pull nandhinis08/projectathon6-miracum1-step2-allpkgs**_

**Comment by NandhiniS08** [comment]
Image build with all the packages
