### ISSUE TITLE
OutOfMemory when downloading Observations

### ISSUE THREAD

**Issue by GeorgFette** [medizininformatik-initiative/Projectathon6-miracum1#13]
Ich habe eine OutOfMemory-Exception bekommen beim Runterladen der Observations.
Der Docker-Server hat eigentlich 100GB RAM zugestanden.
Von diesen hat der FHIR-Server der auf derselben Maschine läuft 20GB in Beschlag.
Ich kann leider nicht mehr nachvollziehen wie der Zustand des Auswertungs-Containers kurz vorm Abbruch war, da sich dieser durch den Fehler beendet hat.
Beim erneuten Start des Auswertungscontainers beginnt der komplette Extraktionsprozess von neuem, so dass ich jetzt erstmal wieder abwarte um zu schauen was diesen Durchlauf passiert. Vielleicht geht es diesmal.
Der erste Schritt der Extraktion der Daten hat ca. 4 Stunden gedauert.

**Comment by NandhiniS08** [comment]
For the step2, we are not extracting observation resources. Only encounter, condit,ion and patient resources. Are you pulling the image fthe rom docker hub?  (docker pull nandhinis08/projectathon6-miracum1-step2)
The folder should be changed to step2 and then the docker-compose should be done

**Comment by GeorgFette** [comment]
Oh, I was running the step1 routines. Sorry
