### ISSUE TITLE
R Umgebung

### ISSUE THREAD

**Issue by stwojke** [medizininformatik-initiative/Projectathon6-miracum1#14]
Hallo,

leider ist meine bisher genutzte Linux R Umgebung nicht mehr verfügbar und ich muss das ganze neu aufsetzen.
Auf einer Windows Umgebung gibt es Probleme beim automatischen Installieren der Packages-
Gibt es irgendwo eine Kurzdoku zur Installation und den Voraussetzungen bzgl. der zu verwendenden R-Version, dem auszuwählendem CRAN Mirror etc.
Bin leider R Neuling...

Lieben Dank & Grüße,
stephan.wojke@kgu.de

**Comment by NandhiniS08** [comment]
Sie können das Skript aus Schritt 2 in einer Windows-Umgebung ausführen, in dem Sie Base R und Rstudio installieren (siehe den folgenden Link). Nach der Installation können Sie das Batch-Skript verwenden, um die Skripte auszuführen.  
https://teacherscollege.screenstepslive.com/a/1108074-install-r-and-r-studio-for-windows

1. Change the folder to step2 and run the runMIRACUM_select_step2 (batch file)
The step2 scripts automatically installs the needed packages and proceeds for the further steps

**Comment by stwojke** [comment]
Ich werde die R-Windows Umgebung mit der neuesten R Version nochmal frisch aufsetzen. Wir haben scheinbar aber aktuell auch Probleme mit unserem Proxy, was das Nachladen von Libs behindert...

**Comment by NandhiniS08** [comment]
Können Sie einmal versuchen, ohne http_proxy, https_proxy zu setzen? Ich meine, sie leer zu lassen ("").

**Comment by stwojke** [comment]
Im Windows Batch gibt es diese Umgebungsvariablen ja nicht. Um Packages wie "fhircrackr" zu laden muss ich zwingend über den Proxy gehen. Wir haben hier scheinbar gerade ein generelles Problem, da auch meine bisher verwendete R Umgebung unter Linux   nicht mehr wie gewohnt funktioniert. Ich warte mal etwas ab, bis sich die Netzwerker melden...
Welche R Version muss ich denn mindestens einsetzen?

**Comment by NandhiniS08** [comment]
R-4.1.1

**Comment by stwojke** [comment]
Danke
