### ISSUE TITLE
Do not search for lists of codes

### ISSUE THREAD

**Issue by stolzA** [medizininformatik-initiative/Projectathon6-miracum1#19]
The central fhir search for encounters has a list of codes as a search parameter. The script should loop over all codes in the list, ask for each code separately, and combine the results afterwards.

Similar fhir search requests should be handled the same way.

Reason: HAPI crashes when the fhir search requests are to complicated (in this case to many codes)

**Comment by NandhiniS08** [comment]
Loop through every ICD in a single request
