### ISSUE TITLE
Fehler in seq.int(0, to0 - from, by) : 'to' muss eine endliche Zahl sein

### ISSUE THREAD

**Issue by stwojke** [medizininformatik-initiative/Projectathon6-miracum1#21]
Hallo zusammen,

ich bekomme hier in Frankfurt nach einigen Minuten folgende Fehlermeldung und Warnungen bei Ausführung
des "step2" Skripts :

{...}
Download completed. All available bundles were downloaded.
Cracking 24 Encounters' Bundles on a WINDOWS-Engine using 1/1 CPU ... 
Cracking 24 Patients' Bundles on a WINDOWS-Engine using 1/1 CPU ... 
Cracking 24 Conditions' Bundles on a WINDOWS-Engine using 1/1 CPU ... 
Time difference of 5.585685 mins
[1] "Data selection done"
[1] "loading stroke cohort"
[1] "extracting lat and long based on PLZ"
[1] "stroke daily counts - three different outputs"
Fehler in seq.int(0, to0 - from, by) : 'to' muss eine endliche Zahl sein
Zusätzlich: Warnmeldungen:
1: `fhir_style()` was deprecated in fhircrackr 2.0.0.
i Please code style elements directly in fhir_table_description().
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
2: The `style` argument of `fhir_table_description()` is deprecated as of fhircrackr 2.0.0.
i Please code style elements directly in the table description. Overwriting fhir_table_descriptions arguments for now.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
3: In min.default(numeric(0), na.rm = FALSE) :
  kein nicht-fehlendes Argument für min; gebe Inf zurück
4: All formats failed to parse. No formats found. 
5: In max.default(numeric(0), na.rm = FALSE) :
  kein nicht-fehlendes Argument für max; gebe -Inf zurück
6: All formats failed to parse. No formats found. 

Grüße,
S. Wojke

**Comment by NandhiniS08** [comment]
Ein ähnliches Problem hatten wir auch bei der LMU. Dies wurde mit dem letzten Update behoben. 

Könnten Sie die neueste Version herunterladen und ausführen?

**Comment by mematt** [comment]
Lieber Herr Wojke,

Frankfurt hat glaube ich nur 2 stellige PLZ-Daten im DIZ oder?  
PLZs werden mit 0 aufgefüllt bis 5-stellig in [line 44](https://github.com/medizininformatik-initiative/Projectathon6-miracum1/blob/5c7260bb4d461b6fd1b28914c50f6920a5772630/step2/3_feature_extraction.R#L44), daher sollten nicht das Problem sein.

Der Fehler liegt m.E. am ehesten bei `$Date` in `line 60` und [line 70](https://github.com/medizininformatik-initiative/Projectathon6-miracum1/blob/5c7260bb4d461b6fd1b28914c50f6920a5772630/step2/3_feature_extraction.R#L70), wenn das Zeitfenster der lokalen Daten nicht den gesamten Range von 2015.01.01-2021.12.31 covert, können NAs auftauchen, weshalb die seq() Funktion den Fehler liefert. 

Wie Fr. Santhanam (@NandhiniS08) schon schreibt, hatten wir ein ähnliches Problem bei der LMU und haben das Skript letzte Woche geupdatet.

Falls, nach der neuen Ausführung, der Fehler weiterhin besteht, hätten Sie Zeit für eine Debugging Session i.R.v. einem Videocall?

Vielen Dank für Ihre Mühen. 

Beste Grüße
M. Maros

**Comment by stwojke** [comment]
Lieben Dank für die schnellen Antworten. Ja, wir haben lediglich 2 stellige PLZ-Daten. Ich werden dann nochmal mit dem Update testen.

**Comment by stwojke** [comment]
Jetzt bekomme ich leider ziemlich direkt ein anderes Problem:

{...}
Lade nötiges Paket: pacman
[1] "Installation done"
Fehler in if (max_bundles < Inf) { : Argument hat Länge 0
Zusätzlich: Warnmeldungen:
1: `fhir_style()` was deprecated in fhircrackr 2.0.0.
i Please code style elements directly in fhir_table_description().
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
generated. 
2: The `style` argument of `fhir_table_description()` is deprecated as of
fhircrackr 2.0.0.
i Please code style elements directly in the table description. Overwriting
  fhir_table_descriptions arguments for now.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
generated. 
>

**Comment by NandhiniS08** [comment]
Es gibt einen neuen Parameter in config.yml 
max_bundles = 50. 

Bitte kopieren Sie die neueste config_default.yml in die config.yml und aktualisieren Sie die Site-spezifischen Informationen.

**Comment by stwojke** [comment]
Ok, den Parameter hatte ich übersehen, sorry.
Jetzt bekomme ich allerdings einen http 503 Response.
Mittels Browser auf dem selben Rechner bekomme ich mit dem protokollierten FHIR request relativ zügig eine ordentliche Antwort.

{...}
Starting download of 50 bundles of resource type Encounter from FHIR base URL http://172.16.100.109:5050/.

This may take a while...
bundle[1](1): http://172.16.100.109:5050/fhir/Encounter?date=ge2015-01-01&date=le2021-12-31&diagnosis:Condition.code=I60.0,I60.1,I60.2,I60.3,I60.4,I60.5,I60.6,I60.7,I60.8,I60.9,I61.0,I61.1,I61.2,I61.3,I61.4,I61.5,I61.6,I61.8,I61.9,I63.0,I63.1,I63.2,I63.3,I63.4,I63.5,I63.6,I63.8,I63.9,I67.80!&_include=Encounter:patient&_include=Encounter:diagnosis
Fehler in check_response(response = response, log_errors = log_errors) : 
  Your request generated a server error, HTTP code 503. For more information see the generated error file.

Im Logfile steht:
{...}
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
{...}

Der Service ist aber da. Wie gesagt funktioniert der Request im Browser. Gibt es irgendwelche zu kleinen Timeout Settings?

**Comment by NandhiniS08** [comment]
Können Sie versuchen, den Wert für max_bundles auf einen niedrigeren Wert zu setzen, z. B. 20

**Comment by stwojke** [comment]
Das Skript läuft jetzt erstmal weiter. Das no_proxy Setting hat nicht richtig gegriffen und er hatte versucht mittels Proxy mit dem FHIR Server zu kommunizieren...

**Comment by stwojke** [comment]
Nun kommt folgendes:

{...}
Time difference of 5.178828 mins
[1] "Data selection done"
[1] "loading stroke cohort"
[1] " Handling missing date"
[1] "Missing dates count after coalesce: 0"
[1] "Stroke cohort rows after removing missing dates: 20054"
[1] "extracting lat and long based on PLZ"
[1] "stroke daily counts - three different outputs"
Fehler in seq.int(0, to0 - from, by) : 'to' muss eine endliche Zahl sein
Zusätzlich: Warnmeldungen:
1: `fhir_style()` was deprecated in fhircrackr 2.0.0.
i Please code style elements directly in fhir_table_description().
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
generated. 
2: The `style` argument of `fhir_table_description()` is deprecated as of
fhircrackr 2.0.0.
i Please code style elements directly in the table description. Overwriting
  fhir_table_descriptions arguments for now.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
generated. 
3: In min.default(numeric(0), na.rm = FALSE) :
  kein nicht-fehlendes Argument für min; gebe Inf zurück
4: All formats failed to parse. No formats found. 
5: In max.default(numeric(0), na.rm = FALSE) :
  kein nicht-fehlendes Argument für max; gebe -Inf zurück
6: All formats failed to parse. No formats found.

**Comment by NandhiniS08** [comment]
The issue is due to some missing plz in  [plz.csv](https://github.com/medizininformatik-initiative/Projectathon6-miracum1/blob/master/step2/data/plz.csv).  Will update with a complete list shortly.

**Comment by NandhiniS08** [comment]
@mematt and @NandhiniS08 : Discussed and decided to update the postal code to the Neurology and neuradiologie clinic of KGU location 

- https://www.kgu.de/einrichtungen/kliniken/zentrum-der-neurologie-und-neurochirurgie/klinik-fuer-neurologie
- https://www.kgu.de/einrichtungen/kliniken/zentrum-der-radiologie/neuroradiologie

Klinik für Neurologie
Universitätsklinikum Frankfurt
Zentrum der Neurologie und Neurochirurgie (Haus 95)
Schleusenweg 2-16
60528 Frankfurt
