### ISSUE TITLE
zip error: Interrupted (aborting)

### ISSUE THREAD

**Issue by joundso** [medizininformatik-initiative/Projectathon6-miracum1#27]
Hi,

the final step of the execution script fails with this error message:

```bash
[1] "Modeling gamboost is done"
[1] "Zip the files in the reults folder to be delivered"


zip error: Interrupted (aborting)
[1] "please upload the zip file (/results) : westorm-step2-results-XXX-2023-04-25-coverage-20xx-20xx-totalcases-XXX"
[1] "Execution is done"
```

Is this known? The `results` folder contains 99 files: 2 excel, 3 pdf and 94 `.rda` files.
Is it OK to manually zip these files and upload the results?

**Comment by NandhiniS08** [comment]
Yes, The zip package used has some dependencies related to the OS. We observed it on other sites too. It should be fine if you can manually zip these files in the zip file name specified in your log (westorm-step2-results-XXX-2023-04-25-coverage-20xx-20xx-totalcases-XXX).  Thanks in advance!

**Comment by joundso** [comment]
OK - thanks!
