### ISSUE TITLE
Make docker image available at docker hub

### ISSUE THREAD

**Issue by palmjulia** [medizininformatik-initiative/Projectathon6-miracum1#3]
The docker Image should be availabe for sites that are not able to build themselves. As an intermin solution @joundso uploded the image [under his dockerhub account](https://hub.docker.com/r/joundso/projectathon6-miracum1) , but there should probably be one under the maintainers (@NandhiniS08 ) account.

You can use the code from #2 , modify it accordingly and merge it into the master.

Necessary steps for this would be:
- Create a DockerHub account
- Change `REGISTRY_PREFIX`  .env-file
- Run build_and_push_image.sh
- Update Readme and docker-compose to new Image `<REGISTRY_PREFIX>/projectathon6-miracum1` 

Thanks @joundso for the help!

**Comment by NandhiniS08** [comment]
Docker image available in docker hub account @NandhiniS08
